---
- name: Define jenkins_build_depends.
  set_fact:
    jenkins_build_depends: "{{ __jenkins_build_depends | list }}"
  when: jenkins_build_depends is not defined

- name: Ensure build dependencies are installed.
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ jenkins_build_depends }}"

- name: Ensure jenkins is installed.
  package:
    name: jenkins
    state: installed
