---
- name: Configure yum for Jenkins repository.
  become: yes
  copy:
    src: jenkins/etc/yum.repos.d/jenkins.repo
    dest: /etc/yum.repos.d
  when: ansible_os_family == 'RedHat'

- name: Configure apt for Jenkins repository.
  become: yes
  copy:
    src: jenkins/etc/apt/sources.list.d/jenkins.list
    dest: /etc/apt/sources.list.d
  when: ansible_os_family == 'Debian'

- name: Configure gpg key for Jenkins repository.
  become: yes
  copy:
    src: jenkins/jenkins-ci.org.key
    dest: /etc/pki/rpm-gpg/
  when: ansible_os_family == 'RedHat'

- name: Import GPG key for Jenkins repo.
  become: yes
  rpm_key:
    key: /etc/pki/rpm-gpg/jenkins-ci.org.key
  when: ansible_os_family == 'RedHat'

- name: Import GPG key for Jenkins repo.
  become: yes
  apt_key:
    data: "{{ lookup('file', 'jenkins/jenkins-ci.org.key') }}"
  when: ansible_os_family == 'Debian'

- name: Update apt cache.
  become: yes
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: install.yml
  become: yes

#- include: config.yml
#  become: yes

- include: service.yml
  become: yes