---
dependencies: []

galaxy_info:
  author: pablotoledo
  description: GitLab Git web interface
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all

