---
- name: Define slave_build_depends.
  set_fact:
    sonar_dependencies: "{{ __sonar_dependencies | list }}"
  when: sonar_dependencies is not defined

- name: Ensure sonar dependencies are installed.
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ sonar_dependencies }}"
