---
- name: Define slave_build_depends.
  set_fact:
    sonar_dependencies: "{{ __sonar_dependencies | list }}"
  when: sonar_dependencies is not defined

- name: Update apt cache.
  become: yes
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Ensure sonar dependencies are installed.
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ sonar_dependencies }}"
