---
- name: Setting Up Sonarqube
  docker_container:
    name: sonarqube
    image: sonarqube
    state: started
    restart: yes
    volumes:
      - "{{ sonarqube_vm_data }}:{{ sonarqube_app_data }}"
      - "{{ sonarqube_vm_logs }}:{{ sonarqube_app_logs }}"
      - "{{ sonarqube_vm_config }}:{{ sonarqube_app_config }}"
    ports:
      - "{{ sonarqube_port }}:9000"


