---

galaxy_info:
  author: pablotoledo
  description: Jenkins CI
  license: "license (BSD, MIT)"
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Fedora
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
    - development
    - packaging
