---
- name: Define slave_build_depends.
  set_fact:
    slave_build_depends: "{{ __slave_build_depends | list }}"
  when: slave_build_depends is not defined

- name: Ensure build dependencies are installed.
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ slave_build_depends }}"

- name: Create standar user to manage this slave
  user: 
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    createhome: yes
    state: present
    shell: /bin/bash
    append: yes
